<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="10" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="107509" started-at="2018-06-11T17:38:59Z" finished-at="2018-06-11T17:40:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="107509" started-at="2018-06-11T17:38:59Z" finished-at="2018-06-11T17:40:46Z">
      <class name="SampleProject.Sample.HerokuapphomeTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:SampleProject.Sample.HerokuapphomeTest@66a3ffec]" name="initialize" is-config="true" duration-ms="32691" started-at="2018-06-11T17:38:59Z" finished-at="2018-06-11T17:39:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:SampleProject.Sample.Tablevalidations@77caeb3e]" name="initialize" is-config="true" duration-ms="58773" started-at="2018-06-11T17:39:31Z" finished-at="2018-06-11T17:40:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="validateImageGithub()[pri:0, instance:SampleProject.Sample.HerokuapphomeTest@66a3ffec]" name="validateImageGithub" duration-ms="441" started-at="2018-06-11T17:40:30Z" finished-at="2018-06-11T17:40:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateImageGithub -->
        <test-method status="PASS" signature="validateLinkelementsselenium()[pri:0, instance:SampleProject.Sample.HerokuapphomeTest@66a3ffec]" name="validateLinkelementsselenium" duration-ms="168" started-at="2018-06-11T17:40:31Z" finished-at="2018-06-11T17:40:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLinkelementsselenium -->
        <test-method status="PASS" signature="validateheader()[pri:0, instance:SampleProject.Sample.HerokuapphomeTest@66a3ffec]" name="validateheader" duration-ms="184" started-at="2018-06-11T17:40:31Z" finished-at="2018-06-11T17:40:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateheader -->
        <test-method status="FAIL" signature="validateurl()[pri:0, instance:SampleProject.Sample.HerokuapphomeTest@66a3ffec]" name="validateurl" duration-ms="20" started-at="2018-06-11T17:40:31Z" finished-at="2018-06-11T17:40:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The Internet] but found [https://the-internet.herokuapp.com/challenging_dom]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The Internet] but found [https://the-internet.herokuapp.com/challenging_dom]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at SampleProject.Sample.HerokuapphomeTest.validateurl(HerokuapphomeTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateurl -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:SampleProject.Sample.HerokuapphomeTest@66a3ffec]" name="teardown" is-config="true" duration-ms="311" started-at="2018-06-11T17:40:46Z" finished-at="2018-06-11T17:40:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="FAIL" signature="teardown()[pri:0, instance:SampleProject.Sample.Tablevalidations@77caeb3e]" name="teardown" is-config="true" duration-ms="2" started-at="2018-06-11T17:40:46Z" finished-at="2018-06-11T17:40:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at SampleProject.Sample.Tablevalidations.teardown(Tablevalidations.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- SampleProject.Sample.HerokuapphomeTest -->
      <class name="SampleProject.Sample.Tablevalidations">
        <test-method status="PASS" signature="validateImageGithub()[pri:0, instance:SampleProject.Sample.Tablevalidations@77caeb3e]" name="validateImageGithub" duration-ms="76" started-at="2018-06-11T17:40:31Z" finished-at="2018-06-11T17:40:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateImageGithub -->
        <test-method status="PASS" signature="validateLinkelementsselenium()[pri:0, instance:SampleProject.Sample.Tablevalidations@77caeb3e]" name="validateLinkelementsselenium" duration-ms="112" started-at="2018-06-11T17:40:31Z" finished-at="2018-06-11T17:40:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLinkelementsselenium -->
        <test-method status="PASS" signature="validateTableheader()[pri:0, instance:SampleProject.Sample.Tablevalidations@77caeb3e]" name="validateTableheader" duration-ms="160" started-at="2018-06-11T17:40:31Z" finished-at="2018-06-11T17:40:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTableheader -->
        <test-method status="PASS" signature="validateTableheadercount()[pri:0, instance:SampleProject.Sample.Tablevalidations@77caeb3e]" name="validateTableheadercount" duration-ms="7305" started-at="2018-06-11T17:40:32Z" finished-at="2018-06-11T17:40:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTableheadercount -->
        <test-method status="PASS" signature="validaterowscount()[pri:0, instance:SampleProject.Sample.Tablevalidations@77caeb3e]" name="validaterowscount" duration-ms="133" started-at="2018-06-11T17:40:39Z" finished-at="2018-06-11T17:40:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validaterowscount -->
        <test-method status="FAIL" signature="validateurl()[pri:0, instance:SampleProject.Sample.Tablevalidations@77caeb3e]" name="validateurl" duration-ms="6955" started-at="2018-06-11T17:40:39Z" finished-at="2018-06-11T17:40:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://the-internet.herokuapp.com/challenging_dom] but found [The Internet]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://the-internet.herokuapp.com/challenging_dom] but found [The Internet]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at SampleProject.Sample.Tablevalidations.validateurl(Tablevalidations.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateurl -->
      </class> <!-- SampleProject.Sample.Tablevalidations -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
